[package]
name = "table-demo-chess"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
lipgloss.workspace = true
lipgloss-table.workspace = true
